version: '3'

services:
  main-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_APP_ID=${GITHUB_APP_ID:?}
      - GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID:?}
      - GITHUB_APP_PRIVATE_KEY_PATH=/secrets/github-app-private-key.pem
      - ALLOWED_INGEST_PAYLOADS=${ALLOWED_INGEST_PAYLOADS:?}
      - APP_LOG_LEVEL=DEBUG
      - SENTRY_DSN=${SENTRY_DSN:?}
      - SENTRY_ENVIRONMENT=dev
    volumes:
      - ./src:/app:ro
      - ${GITHUB_APP_PRIVATE_KEY_PATH:?}:/secrets/github-app-private-key.pem:ro
    command: 
      - "--reload"
